In [ ]:
import pandas as pd
import numpy as np
import sklearn as sk

In [ ]:
# libraries for deep learning - Tensorflow and keras
data = pd.read_csv("/content/drive/MyDrive/Churn_Modelling (1).csv")

In [ ]:
data.head()

RowNumber  CustomerId   Surname  CreditScore  Geography  Gender  Age  \
0          1    15634602  Hargrave          619          0  Female   42   
1          2    15647311      Hill          608          2  Female   41   
2          3    15619304      Onio          502          0  Female   42   
3          4    15701354      Boni          699          0  Female   39   
4          5    15737888  Mitchell          850          2  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
data.isnull().sum() # missing value check

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
# encoding
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
data['Surname'] = le.fit_transform(data['Surname'])

In [ ]:
data.head()

RowNumber  CustomerId  Surname  CreditScore  Geography  Gender  Age  \
0          1    15634602     1115          619          0       0   42   
1          2    15647311     1177          608          2       0   41   
2          3    15619304     2040          502          0       0   42   
3          4    15701354      289          699          0       0   39   
4          5    15737888     1822          850          2       0   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
y = data['EstimatedSalary']
x = data.drop(columns = ['EstimatedSalary'],axis=1)

In [ ]:
from sklearn.preprocessing import scale

In [ ]:
names = x.columns

In [ ]:
x = scale(x)

In [ ]:
x

array([[-1.73187761, -0.78321342, -0.46418322, ...,  0.64609167,
         0.97024255,  1.97716468],
       [-1.7315312 , -0.60653412, -0.3909112 , ..., -1.54776799,
         0.97024255, -0.50577476],
       [-1.73118479, -0.99588476,  0.62898807, ...,  0.64609167,
        -1.03067011,  1.97716468],
       ...,
       [ 1.73118479, -1.47928179,  0.07353887, ..., -1.54776799,
         0.97024255,  1.97716468],
       [ 1.7315312 , -0.11935577,  0.98943914, ...,  0.64609167,
        -1.03067011,  1.97716468],
       [ 1.73187761, -0.87055909,  1.4692527 , ...,  0.64609167,
        -1.03067011, -0.50577476]])

In [ ]:
x = pd.DataFrame(x,columns = names)

In [ ]:
x.head()

RowNumber  CustomerId   Surname  CreditScore  Geography    Gender  \
0  -1.731878   -0.783213 -0.464183    -0.326221  -0.901886 -1.095988   
1  -1.731531   -0.606534 -0.390911    -0.440036   1.515067 -1.095988   
2  -1.731185   -0.995885  0.628988    -1.536794  -0.901886 -1.095988   
3  -1.730838    0.144767 -1.440356     0.501521  -0.901886 -1.095988   
4  -1.730492    0.652659  0.371354     2.063884   1.515067 -1.095988   

        Age    Tenure   Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0  0.293517 -1.041760 -1.225848      -0.911583   0.646092        0.970243   
1  0.198164 -1.387538  0.117350      -0.911583  -1.547768        0.970243   
2  0.293517  1.032908  1.333053       2.527057   0.646092       -1.030670   
3  0.007457 -1.387538 -1.225848       0.807737  -1.547768       -1.030670   
4  0.388871 -1.041760  0.785728      -0.911583   0.646092        0.970243   

     Exited  
0  1.977165  
1 -0.505775  
2  1.977165  
3 -0.505775  
4 -0.505775

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)

In [ ]:
# model building
import tensorflow

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


In [ ]:
model = Sequential()

In [ ]:
#input layer
model.add(Dense(units = 13, kernel_initializer= "random_uniform",activation = 'relu'))

In [ ]:
# hidden layer
model.add(Dense(units = 14, kernel_initializer= "random_uniform",activation = 'relu'))

In [ ]:
# hidden layer
model.add(Dense(units = 15, kernel_initializer= "random_uniform",activation = 'relu'))

In [ ]:
model.add(Dense(units = 1, kernel_initializer= "random_uniform"))

In [ ]:
# compile the model
model.compile(loss='mse',metrics=['mse'],optimizer="adam")

In [ ]:
model.fit(x_train,y_train,epochs=5,batch_size=14)

Epoch 1/5
572/572 [==============================] - 2s 2ms/step - loss: 10381771776.0000 - mse: 10381771776.0000
Epoch 2/5
572/572 [==============================] - 2s 4ms/step - loss: 3428818688.0000 - mse: 3428818688.0000
Epoch 3/5
572/572 [==============================] - 2s 3ms/step - loss: 3379732992.0000 - mse: 3379732992.0000
Epoch 4/5
572/572 [==============================] - 2s 3ms/step - loss: 3369960704.0000 - mse: 3369960704.0000
Epoch 5/5
572/572 [==============================] - 1s 2ms/step - loss: 3359772672.0000 - mse: 3359772416.0000


In [ ]:
pred = model.predict(x_test)

In [ ]:
pred

array([[104289.914],
       [104662.88 ],
       [105233.37 ],
       ...,
       [100680.695],
       [ 94855.18 ],
       [104419.26 ]], dtype=float32)

In [ ]:
y_test = np.array(y_test)

In [ ]:
error = (y_test-pred)

In [ ]:
error

array([[-37494.1340625, -46393.6440625, -60074.0540625, ...,
         36920.2659375,  75231.3259375,   2835.8759375],
       [-37867.1028125, -46766.6128125, -60447.0228125, ...,
         36547.2971875,  74858.3571875,   2462.9071875],
       [-38437.5871875, -47337.0971875, -61017.5071875, ...,
         35976.8128125,  74287.8728125,   1892.4228125],
       ...,
       [-33884.9153125, -42784.4253125, -56464.8353125, ...,
         40529.4846875,  78840.5446875,   6445.0946875],
       [-28059.3996875, -36958.9096875, -50639.3196875, ...,
         46355.0003125,  84666.0603125,  12270.6103125],
       [-37623.4778125, -46522.9878125, -60203.3978125, ...,
         36790.9221875,  75101.9821875,   2706.5321875]])

In [ ]:
from sklearn import metrics

In [ ]:
metrics.mean_squared_error(pred,y_test)

3304921034.843338